## Test Agent Configuration ##

# Host specifies the address the agent will listen on for messages.
host = "localhost"

# port is the port on which the test agent will listen.
port = 3001

# The default name used for wallets created by the test agent.
wallet_name = 'tested-agent'

# The path where wallets will be stored during testing.
wallet_path = ".agent-wallets"

# Specify whether wallets should be deleted after testing.
clear_wallets = true
