[[feature]]
name="connection.manual"
paths=["tests/connection/manual.py"]
description="""

This feature tests the connection protocol using a user input driven method.

See this document for more details:
https://github.com/hyperledger/indy-hipe/blob/a580d00be443990dfcbcf12be5ac85808340de1f/text/connection-protocol/README.md

"""

[[feature]]
name="basicmessage.manual"
paths=["tests/basicmessage/manual.py"]
description="""

This feature tests the BasicMessage protocol defined in the HIPE linked below:
https://github.com/hyperledger/indy-hipe/blob/7df770e4cb3163c1e97b224387fed320bf7d9013/text/basic-message/README.md

"""

[[feature]]
name="trustping.manual"
paths=["tests/trustping/manual.py"]
description="""

This feature tests the TrustPing protocol defined in the HIPE linked below:
https://github.com/hyperledger/indy-hipe/blob/03656b17d36a0a2a5c59a63192ca85c51230b959/text/trust-ping/README.md

"""

[[feature]]
name="unit_tests"
paths=["tests/unit_tests.py"]
description=""
